services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
