FROM node:20.11.1-alpine

# Set working directory
WORKDIR /usr/src/app


# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install 
RUN npm install --save-dev ts-node-dev


# Copy the rest of the application code
COPY . .

# Generate Prisma Client code
RUN npx prisma generate


# Expose the port the app runs on, here, I was using port 3000
EXPOSE 3000

# Command to run the app
CMD [  "npm", "run", "start:migrate:prod"]