FROM node:20.11.1-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install 
RUN npm install --save-dev ts-node-dev
COPY . .
RUN npx prisma generate
EXPOSE 3000
CMD [  "npm", "run", "start:prisma:dev"]