# ---- Build stage ----
FROM node:20-alpine AS build

WORKDIR /usr/src/app

# Install dependencies first
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build the app
RUN npm run build

# ---- Production stage ----
FROM node:20-alpine AS prod

WORKDIR /usr/src/app

# Only copy production deps
COPY package*.json ./
RUN npm ci --omit=dev

# Copy compiled app and Prisma client from build stage
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /usr/src/app/prisma ./prisma

# Expose app port
EXPOSE 3000

CMD [  "npm", "run", "start:prod"]
