name: Deploy frontend and backend to Azure Web Apps

on:
  push:
    branches: ["production"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FRONTEND_APP_NAME: frontend
  BACKEND_APP_NAME: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build and push FRONTEND image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}-frontend:${{ github.sha }}

      - name: Build and push BACKEND image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Deploy FRONTEND to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_APP_NAME }}
          images: "${{ env.REGISTRY }}/${{ env.REPO }}-frontend:${{ github.sha }}"

      - name: Deploy BACKEND to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.BACKEND_APP_NAME }}
          images: "${{ env.REGISTRY }}/${{ env.REPO }}-backend:${{ github.sha }}"
